#!/bin/sh

echo "Running Pint on changed files..."

# Get the list of PHP files that are about to be committed
FILES=$(git diff --cached --name-only --diff-filter=ACM -- "*.php")

# Run Pint on the PHP files

# Iterate through the list of files and add them to the staging area one by one
for FILE in $FILES; do
  ./vendor/bin/pint $FILE
  git add "$FILE"
done

echo "Pint done..."

# Run PHPStan on changed PHP files
echo "Running PHPStan on changed files..."
PHPSTAN_FILES=$(git diff --name-only HEAD | grep -E '\.php$')
if [ -n "$PHPSTAN_FILES" ]; then
  ./vendor/bin/phpstan analyse --memory-limit=2G $PHPSTAN_FILES
  if [ $? -ne 0 ]; then
    echo "PHPStan found errors. Aborting the commit."
    exit 1
  fi
  echo "PHPStan passed!"
else
  echo "No PHP files changed. Skipping PHPStan."
fi

exit 0
