name: laravel_blog_test

services:
  # Laravel App for Testing
  laravel_blog_api_test:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: laravel_blog_api_test
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-coverage}
      - APP_ENV=testing
    depends_on:
      mysql_test:
        condition: service_healthy
      redis_test:
        condition: service_started
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'ok';"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - laravel_blog_api_test_network

  # MySQL Database for Testing
  mysql_test:
    image: mysql:8.0
    container_name: laravel_blog_api_mysql_test
    environment:
      MYSQL_DATABASE: laravel_blog_test
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ../containers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "laravel_user", "-plaravel_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - laravel_blog_api_test_network

  # Redis Cache for Testing
  redis_test:
    image: redis:alpine
    container_name: laravel_blog_api_redis_test
    ports:
      - "6380:6379"
    networks:
      - laravel_blog_api_test_network

networks:
  laravel_blog_api_test_network:
    driver: bridge
